version: "3.8"

services:

  redis:
    image: redis:6.2-alpine
    restart: always
    ports: 
      - "6379:6379"
    command: redis-server --save "" --appendonly no --requirepass redisPassword --

  # api: 
  #   build:
  #     dockerfile: Dockerfile
  #     context: "./backend"
  #   restart: always
  #   depends_on:
  #     - redis 
  #   environment:
  #     REDIS_URL: redis
  #     REDIS_PASSWORD: redisPassword
  #   ports: 
  #     - "5000:5000"
  #   volumes:
  #     - /app/node_modules
  #     - ./backend:/app:delegated 